In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("data\CineStream_Catalog.csv")

In [3]:
df.shape

(524, 23)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ContentID                   524 non-null    str
 1   Title                       524 non-null    str
 2   Type                        524 non-null    str
 3   Genre                       524 non-null    str
 4   Language                    524 non-null    str
 5   Country                     524 non-null    str
 6   Director                    520 non-null    str
 7   CastCount                   524 non-null    int64
 8   ReleaseYear                 524 non-null    int64
 9   AddedDate                   521 non-null    str
 10  RuntimeMinutes              524 non-null    int64
 11  EpisodeCount                524 non-null    int64
 12  AgeRating                   524 non-null    str
 13  IMDbScore                   524 non-null    float64
 14  ViewsMillions               524 non-null    float64
 15  WatchHoursMillions          524 non-null    float64
 16  AvgCompletionPct            524 non-null    int64
 17  AwardsWon                   524 non-null    int64
 18  ProductionCostCr            524 non-null    float64
 19  RevenueCr                   524 non-null    float64
 20  SubscribersGainedThousands  524 non-null    int64
 21  TrendingStatus              524 non-null    str
 22  CriticRating                524 non-null    float64
dtypes: float64(6), int64(7), str(10)
memory usage: 136.1 KB

In [5]:
df.head()

,ContentID,Title,Type,Genre,Language,Country,Director,CastCount,ReleaseYear,AddedDate,...,IMDbScore,ViewsMillions,WatchHoursMillions,AvgCompletionPct,AwardsWon,ProductionCostCr,RevenueCr,SubscribersGainedThousands,TrendingStatus,CriticRating
0,CS-0001,Voyage Whispering II,Movie,Kids,Hindi,India,Akira Brown,3,2024,2020-04-28,...,8.0,25.28,40.81,65,4,56.1,59.5,5873,Classic,7.4
1,CS-0002,Endless River: Reborn,Series,Kids,Korean,South Korea,Riya Patel,6,2017,2020-07-30,...,6.8,24.13,244.20,69,0,43.6,33.6,-1000,New,6.2
2,CS-0003,Distant Letter of the North,Series,Romance,Telugu,India,Liam Iyer,4,2016,2020-08-29,...,7.7,26.77,107.08,80,2,63.6,56.6,1016,Popular,6.9
3,CS-0004,Light Whispering,Series,Animation,English,Australia,Min-jun Khan,5,2020,2020-02-16,...,5.6,8.67,111.27,55,0,44.3,8.6,-1000,Trending,6.6
4,CS-0005,Game Quiet III,Stand-up,Comedy,Hindi,India,Yuki Yilmaz,13,2017,2021-04-20,...,5.5,7.01,5.29,52,0,1.7,10.6,1976,Classic,4.8

In [6]:
df.describe()

,CastCount,ReleaseYear,RuntimeMinutes,EpisodeCount,IMDbScore,ViewsMillions,WatchHoursMillions,AvgCompletionPct,AwardsWon,ProductionCostCr,RevenueCr,SubscribersGainedThousands,CriticRating
count,524.000000,524.000000,524.000000,524.000000,524.000000,524.000000,524.000000,524.000000,524.000000,524.000000,524.000000,524.000000,524.000000
mean,8.761450,2019.465649,481.116412,6.047710,7.091603,16.106183,47.353473,60.303435,1.547710,39.144275,25.017939,3126.242366,6.795038
std,3.801776,2.856806,4371.900126,9.650866,1.131204,9.855031,73.472515,12.973628,1.566748,26.307340,17.876782,4339.804813,1.484984
min,3.000000,2015.000000,50.000000,1.000000,3.700000,0.200000,0.100000,15.000000,0.000000,0.500000,0.100000,-50000.000000,1.700000
25%,5.000000,2017.000000,106.750000,1.000000,6.300000,8.317500,10.692500,52.000000,0.000000,19.175000,11.350000,1126.000000,5.800000
50%,9.000000,2019.500000,149.000000,1.000000,7.100000,15.800000,23.025000,60.000000,1.000000,37.050000,21.850000,3241.000000,6.700000
75%,12.000000,2022.000000,300.000000,8.000000,7.800000,22.920000,48.557500,69.250000,3.000000,53.650000,34.550000,5270.500000,7.800000
max,15.000000,2024.000000,99999.000000,40.000000,11.400000,56.630000,633.910000,98.000000,9.000000,144.100000,82.300000,11636.000000,12.900000

In [7]:
df.isnull().sum()

ContentID                     0
Title                         0
Type                          0
Genre                         0
Language                      0
Country                       0
Director                      4
CastCount                     0
ReleaseYear                   0
AddedDate                     3
RuntimeMinutes                0
EpisodeCount                  0
AgeRating                     0
IMDbScore                     0
ViewsMillions                 0
WatchHoursMillions            0
AvgCompletionPct              0
AwardsWon                     0
ProductionCostCr              0
RevenueCr                     0
SubscribersGainedThousands    0
TrendingStatus                0
CriticRating                  0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(4)

In [9]:
df["Type"].unique()

df["Genre"].unique()

df["Language"].unique()

df["Country"].unique()

df["AgeRating"].unique()

<ArrowStringArray>
['U/A 13+', 'U/A 7+', 'U/A 16+', 'U', 'A']
Length: 5, dtype: str

## Data Quality Issues

1. Duplicate rows found.
2. Missing Director values.
3. Missing AddedDate values.
4. Trailing spaces in Genre.
5. Trailing spaces in Language.
6. Case mismatch in Type.
7. Invalid IMDbScore values.
8. Invalid CriticRating values.
9. Negative SubscribersGainedThousands.
10. Runtime outlier detected.

In [10]:
text_cols = ["Type","Genre","Language","Country","Director","AgeRating","TrendingStatus"]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

In [11]:
df["Type"] = df["Type"].str.title()

In [12]:
df = df.drop_duplicates()

In [13]:
df["AddedDate"] = pd.to_datetime(
    df["AddedDate"],
    errors="coerce"
)

In [14]:
df.loc[
    (df["IMDbScore"] < 1) |
    (df["IMDbScore"] > 10),
    "IMDbScore"
] = np.nan

In [15]:
df.loc[(df["CriticRating"] < 1) | (df["CriticRating"] > 10), "CriticRating"] = np.nan

In [16]:
df.loc[df["RuntimeMinutes"] > 1000, "RuntimeMinutes"] = np.nan

In [17]:
df.loc[
    df["SubscribersGainedThousands"] < 0,
    "SubscribersGainedThousands"
] = 0

In [18]:
df["Profit_Cr"] = (
    df["RevenueCr"]
    - df["ProductionCostCr"]
)

In [19]:
df["ROI_Pct"] = (
    df["Profit_Cr"]
    / df["ProductionCostCr"]
) * 100

In [20]:
df["Performance_Band"] = np.where(
    df["Profit_Cr"] > 20,
    "Hit",
    np.where(
        df["Profit_Cr"] >= 0,
        "Break-even",
        "Flop"
    )
)

In [22]:
df[[
    "Profit_Cr",
    "ROI_Pct",
    "Performance_Band"
]].head()

   Profit_Cr     ROI_Pct Performance_Band
0        3.4    6.060606       Break-even
1      -10.0  -22.935780             Flop
2       -7.0  -11.006289             Flop
3      -35.7  -80.586907             Flop
4        8.9  523.529412       Break-even

In [24]:
df.to_csv("outputs/cleaned_cinestream.csv",index=False)